//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el7elm.Models
{
    public class doctor
    {
        public int doc_id { get; set; }
        public string name { get; set; }
        public decimal salary { get; set; }
        public string gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public int dept_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string major_job { get; set; }
    }
}