//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el7elm.Models
{
    public class payment
    {
        public int patment_id { get; set; }
        public int patient_id { get; set; }

        public string patient_name { get; set; }
        public decimal amount_to_pay { get; set; }
        public string payment_details { get; set; }
    }
}